import type { Metadata } from "next";
import "@nextdaysite/tailwind-config/global-style";
import UIProvider from "@nextdaysite/ui/provider";
import { inter, lato } from "@nextdaysite/tailwind-config/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lato.variable} antialiased`}>
        {/* /wrap application with UI Provider from @nextdaysite/ui/provider at root */}
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
